check pkg part fixed

diff --git a/ropencv/configure b/ropencv/configure
--- a/ropencv/configure
+++ b/ropencv/configure
@@ -1793,16 +1793,53 @@ $as_echo "no" >&6; }
 fi
 
 
-#if test "$pkgfound"="no"; then
-#  PKGCONF=pkgconfig
-#  AC_CHECK_PROG(pkgfound, [pkgconfig --version], yes, no)
-#fi
+if test "$pkgfound" = "no" ; then
+  PKGCONF=pkgconfig
+  # Extract the first word of "pkgconfig --version", so it can be a program name with args.
+set dummy pkgconfig --version; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if test "${ac_cv_prog_pkgfound+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$pkgfound"; then
+  ac_cv_prog_pkgfound="$pkgfound" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_pkgfound="yes"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
 
-if test "$pkgfound" = "yes"; then
+  test -z "$ac_cv_prog_pkgfound" && ac_cv_prog_pkgfound="no"
+fi
+fi
+pkgfound=$ac_cv_prog_pkgfound
+if test -n "$pkgfound"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $pkgfound" >&5
+$as_echo "$pkgfound" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+fi
+
+if test "$pkgfound"="yes"; then
    if `$PKGCONF --cflags opencv > /dev/null`; then
      echo "** OpenCV found by $PKGCONF"
      COMPILERFLAGS="`$PKGCONF --cflags opencv`"
-     CFLAGS="-DUSE_OPENCV ${COMPILERFLAGS} ${CFLAGS}"
+     CFLAGS="${COMPILERFLAGS} ${CFLAGS}"
      CXXFLAGS="${COMPILERFLAGS} ${CXXFLAGS}"
      LINKERFLAGS="`$PKGCONF --libs opencv`"
      LIBS="${LINKERFLAGS} ${LIBS} ${LFALGS}"
@@ -1837,15 +1874,15 @@ fi
 fi
 
 # Find the compiler and compiler flags to use
-#: ${R_HOME=`R RHOME`}
-#if test -z "${R_HOME}"; then
-#  echo "could not determine R_HOME"
-#  exit 1
-#fi
-#CC=`"${R_HOME}/bin/R" CMD config CC`
-#CPP=`"${R_HOME}/bin/R" CMD config CPP`
-##CFLAGS="`"${R_HOME}/bin/R" CMD config CFLAGS` ${CFLAGS}"
-##CXXFLAGS="`"${R_HOME}/bin/R" CMD config CXXFLAGS` ${CXXFLAGS}"
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CPP=`"${R_HOME}/bin/R" CMD config CPP`
+CFLAGS="`"${R_HOME}/bin/R" CMD config CFLAGS` ${CFLAGS}"
+CXXFLAGS="`"${R_HOME}/bin/R" CMD config CXXFLAGS` ${CXXFLAGS}"
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
